### ISSUE TITLE
Doesn't cut some panels

### ISSUE THREAD

**Issue by Grachy** [adenzu/Manga-Panel-Extractor#13]
![002_0](https://github.com/user-attachments/assets/d4f0baeb-2066-47ed-9115-63a8a3b5e50f)

Here is an example that goes out without any cutting at all.

Sometimes it ignores clear panels too... And thats on a obvious and easy to figure out pages.

**Comment by Grachy** [comment]
I can run more tests later. Love this idea, and it would be great to make it work.

**Comment by adenzu** [comment]
Yeah I tested this image myself both on the website and the desktop app and you're right. I will be looking into this. Thanks!

**Comment by adenzu** [comment]
This now should be processed **almost** perfectly with the new release [v2.0.0](https://github.com/adenzu/Manga-Panel-Extractor/releases/tag/v2.0.0). There is still some falsely outputted panel images, but it's much better now.
