### ISSUE TITLE
Non-grayscale

### ISSUE THREAD

**Issue by Stanestane** [adenzu/Manga-Panel-Extractor#2]
Hi,
It seems that your code converts everything to grayscale. However, would it be possible to make a version that works with color images, i.e. produces the output while preserving colors?

**Comment by Stanestane** [comment]
Hi,
Thanks for the quick reply. Looking forward to seeing it in action.

**Comment by adenzu** [comment]
You can now find the executable in [release for v1.1.1](https://github.com/adenzu/Manga-Panel-Extractor/releases/tag/v1.1.1). I tested it myself on a Windows 11 machine and it worked but please issue again if it does not work.
