### ISSUE TITLE
I can't open it

### ISSUE THREAD

**Issue by seanhui96** [adenzu/Manga-Panel-Extractor#20]
![image](https://github.com/user-attachments/assets/e0447b46-45fd-453a-8823-5edec23c9a61)
![image_2024-12-21_122817543](https://github.com/user-attachments/assets/c7fe29e2-5930-468b-8b03-10fc7fa3b2ee)

So I already extract the zip file, and when I open Manga Panel Extractor.exe. It always shown 12% then it crushed could not able to open the manga panel extractor at all.

**Comment by adenzu** [comment]
Thanks! Does it open a window showing any error log? If so can you share? 

Until the issue is fixed, you can use 1.X.X versions (preferably the latest) of the application. Sorry for the trouble.

**Comment by seanhui96** [comment]
no error it just automatically close, currenlt i using 1.3 version
