### ISSUE TITLE
Crash when running python code on Windows 10

### ISSUE THREAD

**Issue by Stanestane** [adenzu/Manga-Panel-Extractor#4]
Trying to run Python code results in the following error:
D:\Manga-Panel-Extractor>python main.py -g
Traceback (most recent call last):
  File "D:\Manga-Panel-Extractor\main.py", line 374, in run
    for i, image in enumerate(load_images(self.input_dir)):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Manga-Panel-Extractor\main.py", line 90, in load_images
    return [load_image(directory_path, image_name, convert_to_grayscale) for image_name in image_names]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Manga-Panel-Extractor\main.py", line 74, in load_image
    return ImageWithFilename(image, image_name, convert_to_grayscale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ImageWithFilename.__init__() takes 3 positional arguments but 4 were given

**Comment by adenzu** [comment]
Yeah my foolish mistake. I fixed the code but I can't give an exact time for the compiled release for I don't have an immediate access to a Windows machine. Thanks for the error message, greatly appreciated.

**Comment by adenzu** [comment]
It should be now fixed. [Here](https://github.com/adenzu/Manga-Panel-Extractor/releases/tag/v1.1.1) you can find the new executables. I've tried both on Ubuntu 22.04 and Windows 10 respectively with the images in [test-in](test-in), they seem to be working. Thanks for your patience.
