### ISSUE TITLE
Crashing and Problems

### ISSUE THREAD

**Issue by victorguima12** [adenzu/Manga-Panel-Extractor#6]
When i activate the option to check for joint pannels it always crash, also when it fails to extract a panel instead of making a copy of the original one to preserve order it just skips it, fixing those would make the program much better

**Comment by adenzu** [comment]
Thank you for letting me know. I will look into this ASAP and update here.

**Comment by Nurikk01** [comment]
> When i activate the option to check for joint pannels it always crash, also when it fails to extract a panel instead of making a copy of the original one to preserve order it just skips it, fixing those would make the program much better



> When i activate the option to check for joint pannels it always crash, also when it fails to extract a panel instead of making a copy of the original one to preserve order it just skips it, fixing those would make the program much better

Same problem here

**Comment by adenzu** [comment]
With the latest release: [v1.1.2](https://github.com/adenzu/Manga-Panel-Extractor/releases/tag/v1.1.2), this bug is now should be fixed.
