### ISSUE TITLE
is that other option to crop?

### ISSUE THREAD

**Issue by seanhui96** [adenzu/Manga-Panel-Extractor#7]
hi is that anyway just to crop horizontal no vertical crop?
![image_2024-06-03_171941795](https://github.com/adenzu/Manga-Panel-Extractor/assets/171484177/710abd19-b750-48cc-9cd8-b3029ec8417e)

**Comment by seanhui96** [comment]
![Untitled-1](https://github.com/adenzu/Manga-Panel-Extractor/assets/171484177/23211a18-e955-423b-8e34-8ca7fd4e739f)

**Comment by seanhui96** [comment]
I willing pay extra money for that, bro!

**Comment by adenzu** [comment]
As of now there is no option to choose to crop horizontal panels together. But it is a good idea that I shall add.

Thank you for your consideration with payment! Right now there is no way for you to pay me. I might add a link to fund to project's page some day. I'm glad it is any use!

As a side note: Currently I'm in my finals weeks of my university, and I should be graduating in a month. Until then I won't be able to work on this project. But after this period I want to get back to working on the project regularly.

**Comment by adenzu** [comment]
With the last commit ([9c8e6e4](https://github.com/adenzu/Manga-Panel-Extractor/commit/9c8e6e4ebab72c039c47be8f0db1d55f4601d380)), this feature is added fully to the desktop app. 

Although it does not function exactly as described by @seanhui96, the user now can choose to extract panels in groups of vertical stripes or horizontal stripes in single image files. See examples in folders [base-horizontal](https://github.com/adenzu/Manga-Panel-Extractor/tree/main/test-out/base-horizontal) and [base-vertical](https://github.com/adenzu/Manga-Panel-Extractor/tree/main/test-out/base-vertical).

**Comment by seanhui96** [comment]
ok, thank for doing it, it is already added？ I still unable to use the Base-horizontal or Base Vertical feature

**Comment by adenzu** [comment]
I am compiling the executable right now and answer here with the link to it when it's uploaded.

**Comment by adenzu** [comment]
See [latest release](https://github.com/adenzu/Manga-Panel-Extractor/releases/tag/v1.1.4) to install new version and use this feature.
